apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-app
  template:
    metadata:
      labels:
        app: user-management-app
    spec:
      containers:
      - name: user-management-app
        image: <dockerhub-username>/user-management-app:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: user-management-app
